version: "3.4"
services:
  auth_api_server:
    container_name: "auth_api_server"
    build:
      context: ./auth-service
      dockerfile: "Dockerfile.api"
      cache_from:
        - rust:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: on-failure
    links:
      - "mongodb_auth"
      - "redis_auth"
    depends_on:
      - "mongodb_auth"
      - "redis_auth"
    networks:
      - cloud_dev_internal_net
    tty: true
    ports:
      - "8080:8080"

  auth_grpc_server:
    container_name: "auth_grpc_server"
    build:
      context: ./auth-service
      dockerfile: "Dockerfile.grpc"
      cache_from:
        - rust:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: on-failure
    links:
      - "mongodb_auth"
      - "redis_auth"
    depends_on:
      - "mongodb_auth"
      - "redis_auth"
    networks:
      - cloud_dev_internal_net
    tty: true
    ports:
      - "50051:50051"
  redis_auth:
    image: redis:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    volumes:
      - redis_data:/data
    networks:
      - cloud_dev_internal_net

  mongodb_auth:
    image: mongo:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "clouddev"
      MONGO_INITDB_ROOT_PASSWORD: "12345678"
    networks:
      - cloud_dev_internal_net




  product_api:
    container_name: "product-api"
    build:
      context: ./product_service
      dockerfile: "Dockerfile.api"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: on-failure
    links:
      - "auth_grpc_server"
      - "product_service_database"
    depends_on:
      - "auth_grpc_server"
      - "product_service_database"
    networks:
      - cloud_dev_internal_net
    tty: true
    ports:
      - "8000:8000"


  product_grpc:
    container_name: "product-grpc"
    build:
      context: ./product_service
      dockerfile: "Dockerfile.grpc"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: on-failure
    links:
      - "auth_grpc_server"
      - "product_service_database"
    depends_on:
      - "auth_grpc_server"
      - "product_service_database"
    networks:
      - cloud_dev_internal_net
    tty: true
    ports:
      - "50052:50052"

  product_service_database:
    image: postgres:12
    environment:
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'fastapi'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloud_dev_internal_net

networks:
  cloud_dev_internal_net:
    driver: bridge

volumes:
  redis_data:
    external: false
  mongodb_data:
      driver: local
  postgres_data:
      driver: local
